spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/project_kakashi_db?createDatabaseIfNotExist=true
    username: root
    password: 12345
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: a36861c1-bd9d-487d-a161-84b992a3e31d
  expiration: 999999

